### ISSUE TITLE
Annotate_dataloader fails without misc attribute

### ISSUE THREAD

**Issue by lauradmartens** [theislab/sfaira#349]
I wrote a dataloader and ran `validate_dataloader` on my yaml file. The resulting new yaml file does not contain any arguments for `misc` 
```yaml
feature_wise:
    gene_id_ensembl_var_key:
    gene_id_symbols_var_key: "index"
misc:
meta:
    version: "1.0"
```
which causes problems later when running `annotate_dataloader` here since there is no value for misc:
https://github.com/theislab/sfaira/blob/dab9cb3f6d89dc6c6b52f9ce23c9a7e938e4d91b/sfaira/data/utils.py#L121

```py 
TypeError: 'NoneType' object is not iterable
```
